INSERT INTO WALLET (CUSTOMER_NAME, BALANCE, CREATED_AT, UPDATED_AT)
VALUES ('John Smith', 1000.00, NOW(), NOW());

INSERT INTO WALLET (CUSTOMER_NAME, BALANCE, CREATED_AT, UPDATED_AT)
VALUES ('Jane Doe', 500.00, NOW(), NOW());

INSERT INTO TRANSACTION (WALLET_ID, AMOUNT, TRANSACTION_TYPE, TRANSACTION_TIME, CREATED_AT, UPDATED_AT)
VALUES (1, 1000.00, 'CREDIT', NOW(), NOW(), NOW());

INSERT INTO TRANSACTION (WALLET_ID, AMOUNT, TRANSACTION_TYPE, TRANSACTION_TIME, CREATED_AT, UPDATED_AT)
VALUES (2, 500.00, 'DEBIT',NOW(), NOW(), NOW());




